### ISSUE TITLE
Usage with RxJS and API on Express

### ISSUE THREAD

**Issue by ghost** [dinoboff/rx-firebase#6]
Hey,
 I have a `React Universal` project and an using CORS with JWT to authenticate and call `Firebase-admin` from the API. I was wondering if it would be possible for you to tell me if it works the same way with firebase-admin as well.

Thanks,
Rahul Basu

**Comment by dinoboff** [comment]
It works with `firebase-admin`, maybe not prior to v0.5.0:
```js
'use strict';

const admin = require('firebase-admin');
const rx = require('rxjs');
const rxFirebase = require('rx-firebase');

rxFirebase.extend(admin, rx.Observable);

admin.initializeApp({
  databaseURL: 'https://foo.firebaseio.com',
  credential: admin.credential.cert('./service-account.json')
})

const db = admin.database();
const ref = db.ref('/foo');

ref.set({a: 1, b: 2, c: 3}).then(() => {
  ref.observe('child_added').take(3).subscribe({
    next: console.log,
    complete: () => admin.app().delete()
  });
});
```

**Comment by ghost** [comment]
Wow thanks a lot! I shall try it right away.

**Comment by ghost** [comment]
Hey Damien,
 Your example worked like a charm. But due to limited documentation, I am having a bit of a hard time gauging how to use the library to the best. For example, I am trying to do something like this:

**Take snapshot of firebase location 'A' & 'B' & then use lodash to find the common values between both of the returned values earlier and then run a snapshot for each of those common values (& add it to an array) and use an observer to send the final array as response to client once it completes.**

Care to help me out please? 
Also **createUser** works the normal way or how do I use the **User authentication** bits as well?

Thanks,
Rahul

**Comment by dinoboff** [comment]
It only provide observable for auth changes, token changes and queries with:

-`firebase.auth.Auth.prototype.observeAuthState`.
- `firebase.auth.Auth.prototype.observeIdTokenState`.
- `firebase.database.Query.prototype.observe`.
- `firebase.database.Query.prototype.observeChildren`.

`observe` and `observeChildren` take a `selector` option. Set it false if you need to emit snapshot instead of the snapshot value, or a function to do your own unpacking.

I opened to PR to add method however don't you get a promise when creating a user? It usually easy to compose with Observable.
